import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatButtonModule,
  MatIconModule,
  MatCardModule,
  MatFormFieldModule,
  MatInputModule,
  MatListModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatSelectModule,
  MatChipsModule,
  MatOptionModule,
  MatCheckboxModule,
  MatRadioModule,
  MatToolbarModule,
  MatTableModule,
  MatTabsModule,
  MatProgressSpinnerModule,
  MatSidenavModule,
  MatAutocompleteModule,
  MatMenuModule,
  MatSnackBarModule,
  MatDialogModule,
  MatSliderModule,
  MatSortModule,
  MatExpansionModule,
  MatTreeModule,
  MatSlideToggleModule,
  MatPaginatorModule,
  MatProgressBarModule
} from '@angular/material';
import { DialougeComponent } from './dialouge/dialouge.component';

@NgModule({
  declarations: [DialougeComponent],
  imports: [
    CommonModule,
    MatButtonModule,
    MatIconModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatListModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSelectModule,
    MatChipsModule,
    MatOptionModule,
    MatCheckboxModule,
    MatRadioModule,
    MatToolbarModule,
    MatTableModule,
    MatTabsModule,
    MatProgressSpinnerModule,
    MatSidenavModule,
    MatAutocompleteModule,
    MatMenuModule,
    MatSnackBarModule,
    MatDialogModule,
    MatSliderModule,
    MatSortModule,
    MatExpansionModule,
    MatTreeModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatPaginatorModule,
    MatProgressBarModule
  ],
  exports: [
    MatButtonModule,
    MatIconModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatListModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSelectModule,
    MatChipsModule,
    MatOptionModule,
    MatCheckboxModule,
    MatRadioModule,
    MatToolbarModule,
    MatTableModule,
    MatTabsModule,
    MatProgressSpinnerModule,
    MatSidenavModule,
    MatAutocompleteModule,
    MatMenuModule,
    MatSnackBarModule,
    MatDialogModule,
    MatSliderModule,
    MatSortModule,
    MatExpansionModule,
    MatTreeModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatPaginatorModule,
    MatProgressBarModule
  ], entryComponents: [
    DialougeComponent
  ]
})
export class AngularMaterialComponentsModule { }